POST https://localhost:5050/products HTTP/1.1
content-type: application/json

{
    "Name": "Product B",
    "Category": ["head", "shoulders"],
    "Description": "Product B Description",
    "ImageFile": "http://imgur.com/product_b",
    "Price": 9.11
}
