POST http://localhost:5000/products HTTP/1.1
content-type: application/json

{
    "Name": "Product A",
    "Description": "Product A Description",
    "ImageFile": "http://imgur.com/product_a",
    "Price": 9.99
}
