version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  pgadmin:


networks:
  catalog_net:
    driver: bridge
  basket_net:
    driver: bridge
